python fastvideo/sample/sample_t2v_mochi_no_sp.py \
    --model_path data/mochi \
    --prompts  "A hand with delicate fingers picks up a bright yellow lemon from a wooden bowl filled with lemons and sprigs of mint against a peach-colored background. The hand gently tosses the lemon up and catches it, showcasing its smooth texture. A beige string bag sits beside the bowl, adding a rustic touch to the scene. Additional lemons, one halved, are scattered around the base of the bowl. The even lighting enhances the vibrant colors and creates a fresh, inviting atmosphere."   \
    --num_frames 163 \
    --height 480 \
    --width 848 \
    --num_inference_steps 64 \
    --guidance_scale 0.0 \
    --seed 12346 \
    --transformer_path data/outputs/debug/checkpoint-100/transformer \
    --output_path outputs_video/single_no_guidance
