python fastvideo/sample/sample_t2v_mochi.py \
    --model_path data/mochi \
    --prompt "A hand enters the frame, pulling a sheet of plastic wrap over three balls of dough placed on a wooden surface. The plastic wrap is stretched to cover the dough more securely. The hand adjusts the wrap, ensuring that it is tight and smooth over the dough. The scene focuses on the hand's movements as it secures the edges of the plastic wrap. No new objects appear, and the camera remains stationary, focusing on the action of covering the dough." \
    --num_frames 79 \
    --height 480 \
    --width 848 \
    --num_inference_steps 64 \
    --guidance_scale 4.5 \
    --seed 12345 \
    --transformer_path data/outputs/debug_1e-6/checkpoint-100/transformer \
    --output_path 1e-6_step_100.mp4
