recipe:
  family: wan
  method: dmd2

roles:
  student:
    family: wan
    path: Wan-AI/Wan2.1-T2V-1.3B-Diffusers
    trainable: true
  teacher:
    family: wan
    path: Wan-AI/Wan2.1-T2V-14B-Diffusers
    trainable: false
    disable_custom_init_weights: true
  critic:
    family: wan
    path: Wan-AI/Wan2.1-T2V-1.3B-Diffusers
    trainable: true
    disable_custom_init_weights: true

training:
  # Distributed
  num_gpus: 8
  sp_size: 1
  tp_size: 1

  # Data (parquet dataset folder)
  data_path: data/Wan-Syn_77x448x832_600k
  dataloader_num_workers: 4

  # Batch / shape (matches Wan-Syn 77x448x832)
  train_batch_size: 1
  train_sp_batch_size: 1
  gradient_accumulation_steps: 1
  num_latent_t: 20
  num_height: 448
  num_width: 832
  num_frames: 77

  # Output / steps
  output_dir: outputs/phase3.1_wan2.1_dmd2_8steps_wansyn
  max_train_steps: 4000
  seed: 1000
  checkpoints_total_limit: 3

  # Optimizer
  learning_rate: 2.0e-6
  mixed_precision: bf16
  betas: "0.0,0.999"
  weight_decay: 0.01
  lr_scheduler: constant
  lr_warmup_steps: 0
  max_grad_norm: 1.0

  fake_score_learning_rate: 8.0e-6
  fake_score_betas: "0.0,0.999"
  fake_score_lr_scheduler: constant

  # Method-agnostic knobs
  training_cfg_rate: 0.0
  min_timestep_ratio: 0.02
  max_timestep_ratio: 0.98
  enable_gradient_checkpointing_type: full

  # Tracking / validation
  tracker_project_name: phase3.1_wan_dmd2_8steps_wansyn
  wandb_run_name: phase3.1_wan_dmd2_8steps
  log_validation: true
  validation_dataset_file: examples/training/finetune/Wan2.1-VSA/Wan-Syn-Data/validation_4.json
  validation_steps: 50
  validation_sampling_steps: "8"
  validation_guidance_scale: "6.0"

pipeline_config:
  flow_shift: 8
  sampler_kind: sde

method_config:
  rollout_mode: simulate
  generator_update_interval: 5
  real_score_guidance_scale: 3.5
  dmd_denoising_steps: [1000, 850, 700, 550, 350, 275, 200, 125]
