# SPDX-License-Identifier: Apache-2.0
"""Tests for the typed omni request plane (fastvideo/api/omni.py, design.md §6.1)."""
from __future__ import annotations

import pytest

from fastvideo.api.omni import (
    AudioArtifact,
    DiffusionParams,
    ImagePart,
    Modality,
    NodeOverrides,
    OmniChunkEvent,
    OmniFinalEvent,
    OmniOutput,
    OmniProgressEvent,
    OmniRequest,
    OutputSpec,
    StreamSpec,
    TaskType,
    TextPart,
    VideoArtifact,
    infer_task,
    omni_event_from_video_event,
)
from fastvideo.api.results import (
    GenerationResult,
    VideoFinalEvent,
    VideoPartialEvent,
    VideoProgressEvent,
)
from fastvideo.api.schema import GenerationRequest, InputConfig, SamplingConfig


def test_enums_are_strings():
    assert TaskType.T2V == "t2v"
    assert Modality.AUDIO == "audio"
    # str mixin keeps them usable anywhere a string is expected
    assert f"{TaskType.REASON}" == "TaskType.REASON" or TaskType.REASON.value == "reason"
    assert TaskType("i2v") is TaskType.I2V


def test_request_id_autogenerated_and_unique():
    a = OmniRequest(task=TaskType.T2V)
    b = OmniRequest(task=TaskType.T2V)
    assert a.request_id and b.request_id
    assert a.request_id != b.request_id


def test_prompt_and_negative_accessors():
    req = OmniRequest.from_prompt("a cat", TaskType.T2V, negative_prompt="blurry")
    assert req.prompt == "a cat"
    assert req.negative_prompt == "blurry"
    assert req.parts(Modality.TEXT)
    assert req.parts(Modality.IMAGE) == []


def test_positional_text_part_is_text_not_role():
    # role is keyword-only, so the positional arg is the payload
    part = TextPart("hello")
    assert part.text == "hello"
    assert part.role is None


def test_round_trip_through_generation_request():
    req = OmniRequest(
        task=TaskType.T2V,
        inputs=[TextPart("a fox"), TextPart("ugly", role="negative")],
        diffusion=DiffusionParams(steps=30, guidance_scale=6.0, height=480, width=832, num_frames=49),
    )
    legacy = req.to_generation_request()
    assert isinstance(legacy, GenerationRequest)
    assert legacy.prompt == "a fox"
    assert legacy.negative_prompt == "ugly"
    assert legacy.sampling.num_inference_steps == 30
    assert legacy.sampling.guidance_scale == 6.0
    assert legacy.sampling.height == 480
    assert legacy.sampling.num_frames == 49

    back = OmniRequest.from_generation_request(legacy, task=TaskType.T2V)
    assert back.prompt == "a fox"
    assert back.negative_prompt == "ugly"
    assert back.diffusion.steps == 30
    assert back.diffusion.guidance_scale == 6.0
    assert back.diffusion.height == 480
    assert back.diffusion.num_frames == 49


def test_image_input_lowers_and_lifts():
    req = OmniRequest(task=TaskType.I2V, inputs=[TextPart("dance"), ImagePart(path="/tmp/x.png")])
    legacy = req.to_generation_request()
    assert legacy.inputs.image_path == "/tmp/x.png"
    back = OmniRequest.from_generation_request(legacy)
    assert back.task == TaskType.I2V  # inferred from the image input
    assert back.parts(Modality.IMAGE)[0].path == "/tmp/x.png"  # type: ignore[attr-defined]


@pytest.mark.parametrize(
    ("inputs", "sampling", "expected"),
    [
        (InputConfig(), SamplingConfig(num_frames=49), TaskType.T2V),
        (InputConfig(image_path="/a.png"), SamplingConfig(num_frames=49), TaskType.I2V),
        (InputConfig(video_path="/a.mp4"), SamplingConfig(num_frames=49), TaskType.V2V),
        (InputConfig(), SamplingConfig(num_frames=1), TaskType.T2I),
        (InputConfig(image_path="/a.png"), SamplingConfig(num_frames=1), TaskType.I2I),
    ],
)
def test_infer_task_heuristic(inputs, sampling, expected):
    req = GenerationRequest(prompt="x", inputs=inputs, sampling=sampling)
    assert infer_task(req) == expected


def test_named_artifacts_replace_extra_audio():
    result = GenerationResult(
        prompt="song",
        frames="FRAMES",
        audio="WAV",
        audio_sample_rate=44100,
        generation_time=1.5,
        peak_memory_mb=1234.0,
    )
    out = OmniOutput.from_generation_result(result, request_id="r1")
    assert out.request_id == "r1"
    assert isinstance(out.video, VideoArtifact)
    assert out.video.frames == "FRAMES"
    # audio is a first-class artifact carrying its sample rate, not extra["audio"]
    assert isinstance(out.audio, AudioArtifact)
    assert out.audio.sample_rate == 44100
    assert out.audio.source_node == "audio_decode"
    assert out.metrics.generation_time == 1.5
    assert out.metrics.peak_memory_mb == 1234.0


def test_omni_event_from_video_event():
    prog = omni_event_from_video_event(VideoProgressEvent(step=3, total_steps=50, stage="refine"))
    assert isinstance(prog, OmniProgressEvent)
    assert prog.step == 3 and prog.node == "refine"

    chunk = omni_event_from_video_event(VideoPartialEvent(frames="CHUNK", index=2))
    assert isinstance(chunk, OmniChunkEvent)
    assert chunk.modality == Modality.VIDEO and chunk.index == 2 and chunk.payload == "CHUNK"

    final = omni_event_from_video_event(
        VideoFinalEvent(result=GenerationResult(frames="F", audio="A", audio_sample_rate=24000)),
        request_id="rid",
    )
    assert isinstance(final, OmniFinalEvent)
    assert final.output.request_id == "rid"
    assert final.output.audio.sample_rate == 24000


def test_node_overrides_access():
    req = OmniRequest(task=TaskType.T2V, node_params={"refine": NodeOverrides(params={"steps": 8})})
    assert req.node_params["refine"].steps == 8       # attribute access
    assert req.node_params["refine"]["steps"] == 8    # item access
    assert req.node_params["refine"].get("missing", 0) == 0
    with pytest.raises(AttributeError):
        _ = req.node_params["refine"].nonexistent
    # node_params survive the round-trip into stage_overrides
    legacy = req.to_generation_request()
    assert legacy.stage_overrides == {"refine": {"steps": 8}}


def test_output_spec_streaming_flag():
    spec = OutputSpec(modalities=[Modality.VIDEO, Modality.AUDIO])
    assert spec.streaming is False
    spec.stream[Modality.AUDIO] = StreamSpec(enabled=True, chunk_ms=200)
    assert spec.streaming is True
