torchrun --nproc_per_node=2 fastvideo/sample/sample_i2v_wan.py \
    --base_seed 0 \
    --task i2v-14B \
    --size 1280*720 \
    --ckpt_dir /workspace/data/Wan2.1-I2V-14B-720P \
    --dit_fsdp \
    --t5_fsdp \
    --prompt "Summer beach vacation style, a white cat wearing sunglasses sits on a surfboard. The fluffy-furred feline gazes directly at the camera with a relaxed expression. Blurred beach scenery forms the background featuring crystal-clear waters, distant green hills, and a blue sky dotted with white clouds. The cat assumes a naturally relaxed posture, as if savoring the sea breeze and warm sunlight. A close-up shot highlights the feline's intricate details and the refreshing atmosphere of the seaside." \
    --image ./i2v_input.JPG \
    --enable_teacache \
    --rel_l1_thresh 0.19