# SPDX-License-Identifier: Apache-2.0
"""Create a FastVideo-compatible (Diffusers-style) repo for Waypoint-1-Small.

FastVideo expects a `model_index.json` at the model root with module entries in
either:

1) Standard diffusers style:
   "transformer": ["diffusers", "WorldModel"]

2) Modular style (supported by FastVideo):
   "text_encoder": [null, null, {"pretrained_model_name_or_path": "...", "type_hint": ["transformers","UMT5EncoderModel"]}]

This script creates a minimal local directory that can be used with:

    StreamingVideoGenerator.from_pretrained("converted/waypoint_diffusers_stub")

By default this generates a *thin* repo that points components to upstream HF
repos (Overworld + google/umt5-xl) so weights can be auto-downloaded by
FastVideo without requiring manual config creation.

Optionally, you can also *bundle* the transformer weights/config into the repo
directory (useful if you want to publish a `FastVideo/...-Diffusers` model repo
that contains the DiT weights under `transformer/`).
"""

from __future__ import annotations

import argparse
import json
import os
import shutil


LFS_GITATTRIBUTES = """# Auto-generated by convert_waypoint_stub_repo.py
*.safetensors filter=lfs diff=lfs merge=lfs -text
*.bin filter=lfs diff=lfs merge=lfs -text
"""


def _copy_if_exists(src: str, dst: str) -> None:
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Expected file not found: {src}")
    shutil.copy2(src, dst)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        type=str,
        default="converted/waypoint_diffusers_stub",
        help="Output directory for the stub repo.",
    )
    parser.add_argument(
        "--bundle-transformer",
        action="store_true",
        help=(
            "Copy transformer config + safetensors into the output repo under "
            "`transformer/`. Requires --source-weights-dir."
        ),
    )
    parser.add_argument(
        "--bundle-vae",
        action="store_true",
        help=(
            "Copy VAE config + safetensors into the output repo under `vae/`. "
            "Requires --source-weights-dir."
        ),
    )
    parser.add_argument(
        "--source-weights-dir",
        type=str,
        default=None,
        help=(
            "Path to a local Waypoint weights folder, e.g. "
            "`official_weights/Waypoint-1-Small` containing transformer/ and vae/."
        ),
    )
    args = parser.parse_args()

    out_dir = args.out
    os.makedirs(out_dir, exist_ok=True)
    os.makedirs(os.path.join(out_dir, "transformer"), exist_ok=True)
    os.makedirs(os.path.join(out_dir, "vae"), exist_ok=True)

    model_index = {
        "_class_name": "WaypointPipeline",
        "_diffusers_version": "0.36.0",
        # Modules are resolved via FastVideo's modular loader support.
        "transformer": [
            None,
            None,
            {
                "pretrained_model_name_or_path": "Overworld/Waypoint-1-Small",
                "subfolder": "transformer",
                "type_hint": ["diffusers", "WorldModel"],
            },
        ],
        "vae": [
            None,
            None,
            {
                "pretrained_model_name_or_path": "Overworld/Waypoint-1-Small",
                "subfolder": "vae",
                "type_hint": ["diffusers", "WorldEngineVAE"],
            },
        ],
        "text_encoder": [
            None,
            None,
            {
                "pretrained_model_name_or_path": "google/umt5-xl",
                "type_hint": ["transformers", "UMT5EncoderModel"],
            },
        ],
        "tokenizer": [
            None,
            None,
            {
                "pretrained_model_name_or_path": "google/umt5-xl",
                "type_hint": ["transformers", "AutoTokenizer"],
            },
        ],
    }

    with open(os.path.join(out_dir, "model_index.json"), "w",
              encoding="utf-8") as f:
        json.dump(model_index, f, indent=2)

    # HF LFS helpers (only relevant if you publish this as a HF repo).
    with open(os.path.join(out_dir, ".gitattributes"), "w", encoding="utf-8") as f:
        f.write(LFS_GITATTRIBUTES)

    # Optionally bundle weights into this repo.
    if args.bundle_transformer or args.bundle_vae:
        if args.source_weights_dir is None:
            raise SystemExit("--source-weights-dir is required when bundling weights.")

        src_root = args.source_weights_dir
        if args.bundle_transformer:
            _copy_if_exists(
                os.path.join(src_root, "transformer", "config.json"),
                os.path.join(out_dir, "transformer", "config.json"),
            )
            _copy_if_exists(
                os.path.join(src_root, "transformer", "diffusion_pytorch_model.safetensors"),
                os.path.join(out_dir, "transformer", "diffusion_pytorch_model.safetensors"),
            )

        if args.bundle_vae:
            _copy_if_exists(
                os.path.join(src_root, "vae", "config.json"),
                os.path.join(out_dir, "vae", "config.json"),
            )
            _copy_if_exists(
                os.path.join(src_root, "vae", "diffusion_pytorch_model.safetensors"),
                os.path.join(out_dir, "vae", "diffusion_pytorch_model.safetensors"),
            )

    print(f"Wrote stub repo to: {out_dir}")
    print("Next:")
    print(
        f"  python examples/inference/basic/basic_waypoint_streaming.py  # after setting MODEL_ID to {out_dir}"
    )


if __name__ == "__main__":
    main()


