name: Python Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or any version you need

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pylint
          # If you have a requirements.txt:
          # pip install -r requirements.txt
          pip install -e .

      - name: Run PyLint
        run: |
          pylint --exit-zero **/*.py
          # Remove --exit-zero if you want the workflow to fail on lint errors
